spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/ai-service-fitness-suggession
      database: ai-service-fitness-suggession
  kafka:
    bootstrap-server: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.ai_service.model.Activity


    topic:
      name: activity-events

  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

