spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/ai-service-fitness-suggession
      database: ai-service-fitness-suggession

  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

