spring:
  application:
    name: user-service

#  datasource:
#    url: jdbc:postgresql://localhost:5432/fitness-micro-user
#    username: postgres
#    password: root
#    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/fitness-micro-user
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
