spring:
  application:
    name: user-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/fitness-micro-user
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

